if:
  type = push
os:
  - linux
  - osx
language: rust
rust:
  - stable
git:
  depth: false
matrix:
  fast_finish: true
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ci/install.sh; fi
before_script:
  - rustup component add clippy-preview
script:
  - cargo update
  # in order to also check tests and none-default crate features, use
  - cargo clippy --all-targets --all-features -- -D warnings
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ci/script_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ci/script_osx.sh; fi
before_deploy:
  - bash ci/prepare-deploy.sh
deploy:
  provider: releases
  file_glob: true
  file: archives/*.tar.gz
  skip_cleanup: true
  api_key:
    secure: $GITHUB_RELEASES_TOKEN
  on:
    tags: true
