#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

cp rusmtpd /usr/local/bin/rusmtpd
cp rusmtpc /usr/local/bin/rusmtpc
test -z "$HOME"/.rusmtprc || cp rusmtprc.default "$HOME"/.rusmtprc
man_path=$(manpath | cut -d':' -f1)
cp rusmtpd.1 "$man_path/"
cp rusmtpc.1 "$man_path/"
