[package]
name = "main"
version = "4.1.0-SNAPSHOT"
authors = ["amanjpro <http://www.amanj.me>"]

[[bin]]
name = "rusmtpd"
path = "src/rusmtpd.rs"

[[bin]]
name = "rusmtpc"
path = "src/rusmtpc.rs"

[dependencies]
serde_json = "1.0.9"
common = { path = "../common" }
