[package]
name = "main"
version = "1.0.0"
authors = ["amanjpro <http://www.amanj.me>"]

[[bin]]
name = "smtpd"
path = "src/smtpd.rs"

[[bin]]
name = "smtpc"
path = "src/smtpc.rs"

[dependencies]
docopt = "0.8"
rust-ini = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.9"
common = { path = "../common" }
