[package]
name = "main"
version = "2.1.0"
authors = ["amanjpro <http://www.amanj.me>"]

[[bin]]
name = "smtpd"
path = "src/smtpd.rs"

[[bin]]
name = "smtpc"
path = "src/smtpc.rs"

[dependencies]
secstr = "0.3.0"
serde_json = "1.0.9"
common = { path = "../common" }
esmtp_client = { path = "../esmtp-client" }
