[package]
name = "main"
version = "0.1.0-SNAPSHOT"
authors = ["amanjpro <http://www.amanj.me>"]

[[bin]]
name = "rusmtpd"
path = "src/rusmtpd.rs"

[[bin]]
name = "rusmtpc"
path = "src/rusmtpc.rs"

[dependencies]
fs2 = "0.4"
common = { path = "../common" }
