#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

cp rusmtpd /usr/local/bin/rusmtpd
cp rusmtpc /usr/local/bin/rusmtpc
test -z "$HOME"/.rusmtprc || cp rusmtprc.default "$HOME"/.rusmtprc
man_path="/usr/share/man/man1/"
cp rusmtpd.1 "$man_path/"
cp rusmtpc.1 "$man_path/"
