[package]
name = "esmtp-client"
version = "1.0.0-SNAPSHOT"
authors = ["amanjpro <http://www.amanj.me>"]

[[bin]]
name = "test"
path = "src/lib.rs"

[dependencies]
native-tls = "0.1"
base64 = "0.9.0"
secstr = "0.3.0"
