[package]
name = "protocol"
version = "0.1.1"
authors = ["amanjpro <http://www.amanj.me>"]

[features]
vendored = ["native-tls/vendored"]

[dependencies]
log = "0.4"
native-tls = "0.2"
lazy_static = "1.2"
regex = "1"
base64 = "0.10"
