.TH RUSMTPD 1
.SH NAME
rusmtpd \- A simple and secure SMTP-client daemon.

.SH SYNOPSIS
.B rusmtpd
[\fB\-\-rusmtprc=PATH_TO_SMTPDRC]

.SH DESCRIPTION
.B rusmtpd
A simple standalone SMTP daemon.

A typical scenario of using rusmtp is with clients like NeoMutt, where you do
not store your passwords unencrypted, but you still wish to get all the
benefits of using NeoMutt.

A typical installation would be as follows:

.IP \[bu] 4
Add (set sendmail="/PATH/TO/rusmtp") in muttrc.
.IP \[bu]
Using GnuGP, encrypt your password and save the encrypted password.
.IP \[bu]
.TP
Add (passwordeval=gpg --quiet --no-tty --decrypt /PATH/TO/ENCRYPTED-PASSWORD.gpg) to
rusmtprc for each account.
.IP \[bu]
Add the password to decrypt the encrypted password in gpg-agent, to avoid entering
the password upon starting the deamon.
.IP \[bu]
Make rusmtpd to startup upon boot.

.SH OPTIONS
.TP
.BR \-\-rusmtprc=\fIPATH_TO_SMTPDRC\fR
An option to specify an alternative configuration file for the daemon. By default the daemon reads from $HOME/.rusmtprc, but this options overrides it. An example configuration file is already installed in $HOME/.rusmtprc.

.SH LIMITATIONS

At its current state, the builtin SMTP client only supports ESMTP and
only supports LOGIN (i.e. it uses username and password to authenticate
the connection).

.SH SEE ALSO
.B rusmtpc(1)

.SH SOURCE CODE
.B https://github.com/amanjpro/rusmtp
