.TH SMTPC 1
.SH NAME
smtpc \- An smtp client to send emails through an SMTP-client daemon (smtpd).

.SH SYNOPSIS
.B smtpc
[\fB\-\-smtpdrc=PATH_TO_SMTPDRC]
[\fB\-\-account=ACCOUNT_NAME]
[\-\-]
.IR recipients ...

.SH DESCRIPTION
.B smtpc
A simple client to talk to the smtpd daemon for sending emails.

.SH OPTIONS
.TP
.BR \-\-smtpdrc=\fIPATH_TO_SMTPDRC\fR
An option to specify an alternative configuration file for the daemon. By default the daemon reads from $HOME/.smtpdrc, but this options overrides it. An example configuration file is already installed in $HOME/.smtpdrc.
.TP
.BR \-\-account=\fIACCOUNT_NAME\fR
The account on which the email should be sent. If none is provided, the
default account would.
.TP
.BR \-\-
A \-\- signals the end of options and disables further option
processing.  Any arguments after the \-\- are treated as recipients.

.SH SEE ALSO
.B smtpd(1)
