[package]
name = "common"
version = "4.1.0-SNAPSHOT"
authors = ["amanjpro <http://www.amanj.me>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.9"
rust-ini = "0.10"
docopt = "1.0"
dirs = "1.0"
ring = "0.13"
rand = "0.5"
protocol = { path = "../protocol" }
