[package]
name = "common"
version = "0.1.0-beta2"
authors = ["amanjpro <http://www.amanj.me>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
rust-ini = "0.13"
docopt = "1.0"
dirs = "1.0"
ring = "0.13"
rand = "0.5"
log = "0.4"
