[package]
name = "common"
version = "0.1.0"
authors = ["amanjpro <amanj.sherwany@adgear.com>"]

[dependencies]
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`
